apiVersion: v1
kind: Service
metadata:
  name: task-management-ui-service
spec:
  selector:
    app: task-management-ui
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
